---
name: checks

'on':
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  scripted-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Install python-tinycss2
        run: sudo apt-get install -y python3-tinycss2
      - name: Verify scripted tests
        run: tests/scripted/verify
      - name: Run check-strings
        run: tests/scripted/check-strings
      - name: Run check-namespace
        run: tests/scripted/check-namespace

  shellcheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: koalaman/shellcheck-alpine:v0.9.0
    steps:
      - name: Check out
        uses: actions/checkout@v7
      - name: Run shellcheck
        run: |
          shellcheck \
            $(find "./cmake/" -type f -name '*.sh' -o -name "*.sh.in") \
            doc/bash-completion/mxm \
            buildtools/update_locales

  yamllint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out
        uses: actions/checkout@v7
      - name: Run yamllint
        run: for i in $(git ls-files '*.yml'); do yamllint $i; done
