---
name: doxygen

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build Doxygen documentation
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: read

    steps:
      - name: Check out
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends --no-install-suggests graphviz

      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v2
        with:
          version: "1.18.0"

      - name: Configure
        run: cmake -S doc -B build

      - name: Build docs
        run: cmake --build build --target doc

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload generated website
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/doc/html

  deploy:
    name: Deploy Doxygen docs to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
